### PR TITLE
Create form

### PR DESCRIPTION
**Pull request by stephnna**
Hi code reviewer,

I created a method called current_user in the ApplicationController to make current user data available to all controllers.
It returns the first user from the database.
Then I created  forms to perform the following functions:
 - Post on behalf of the current_user (using the method in the ApplicationController).
 -   comment on behalf of the current_user (using the method in the ApplicationController).
 - 
 - Finally, Users can add likes to the Posts.
Kindly review as required
Thanks!

### CODE REVIEW

**Review by rotimiazeez — APPROVED** [review]
# Hi @stephnna 😉. 
## To Highlight 🔥
- No linter error ✔️ 
- All project requirements are met 👍🏽
- Good PR description 👏🏽
- Good commit messages ✋🏽
### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
Hi @stephnna 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pr, that has a deleted branch and does not have the updated microverse readme template, please submit a new pull request so that if there are any changes they can be implemented there 👍🏿 
- Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, 
this is a requirement to get a review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by stephnna** [comment]
Hi @prolajumokeoni 
 It is so because I repeated the module, and Microverse said that I could still resubmit all my initial code, and pull requests. If you check the pull request, you will notice that there are about 10 of them and they have all been approved during the previous module. Please, in other to avoid code conflict and unnecessary hard labour, go ahead and approve it since the project was reviewed initially by two of your colleagues and the last reviewer before you, approved it. In addition to that, all the last week's projects I resubmitted were approved again by your colleagues without invalidating the work. Thanks!

**Comment by rustam-tolipov** [comment]
Hello @stephnna, I hope you are doing well :). I can see that your project has already been approved (before you repeat the module). After you restart your module, you are saying that you got a confirmation from Student Success to reuse the code again, right? If it is, could you share the message by sending a screenshot of it? If they confirmed it, I can approve your code in this place again. :)

**Comment by stephnna** [comment]
Hi @Rustamxon7 

find the screenshot below

8E8C0852-093A-4605-A563-44CD4FFF9718

**Review by rustam-tolipov — COMMENTED** [review]
Hi @stephnna, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Developer-512px-10

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
