### PR TITLE
Controller spec

### PR DESCRIPTION
**Pull request by stephnna**
Hi code reviewer,

I tested for the correct response status.
And if the response body includes the correct placeholder text.

Kindly review as neccessary
Thanks!

### CODE REVIEW

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @stephnna, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by muneebulrehman** [comment]
Hi @stephnna , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, for which i can't request any changes (if i do) since all the code has already been merged in the default branch and the current branch is deleted.

Ps. I invalidated this PR after asking a senior code reviewer and he explicitly said to invalidate it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by stephnna** [comment]
@muneebulrehman

Hi dear, your observation that all code has already been merged in the default branch and the current branch is deleted is correct.

If you had looked above, you would have noticed that the project had been approved. I repeated the module, and Microverse said that I could still resubmit all my initial code, and pull request. If you check the pull request, you will notice that there are about 10 of them and they have all been approved during the previous module. Please, in other to avoid code conflict and unnecessary hard labour, go ahead and approve it since the project was reviewed initially by two of your colleagues and the last reviewer before you approved it Thanks!

**Review by cynthiainga — COMMENTED** [review]
Hi @stephnna, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- [ ] Descriptive PR ✔️ 
- [ ] Correct Gitflow ✔️ 
- [ ] Good commit history ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by muneebulrehman** [comment]
> @muneebulrehman
> 
> Hi dear, your observation that all code has already been merged in the default branch and the current branch is deleted is correct.
> 
> If you had looked above, you would have noticed that the project had been approved. I repeated the module, and Microverse said that I could still resubmit all my initial code, and pull request. If you check the pull request, you will notice that there are about 10 of them and they have all been approved during the previous module. Please, in other to avoid code conflict and unnecessary hard labour, go ahead and approve it since the project was reviewed initially by two of your colleagues and the last reviewer before you approved it Thanks!

Hey @stephnna, I invalidated your PR after I spoke to a senior code reviewer.

**Pull request merged**
